apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-database
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup {{ .Release.Name }}-{{ .Values.global.postgresql.postgresqlHost }}; do echo waiting for mydb; sleep 2; done"]
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "BOT_TOKEN"
              value: {{ .Values.botToken }}
            - name: "PGHOST"
              value: "{{ .Release.Name }}-{{ .Values.global.postgresql.postgresqlHost }}"
            - name: "PGUSER"
              value: {{ .Values.global.postgresql.postgresqlUsername }}
            - name: "PGPASSWORD"
              valueFrom:
                secretKeyRef:
                  key: pass
                  name: {{ .Release.Name }}-auth
            - name: "PGDATABASE"
              value: {{ .Values.global.postgresql.postgresqlDatabase }}
            - name: "PGPORT"
              value: {{ .Values.global.postgresql.servicePort | default 5432 | quote }}
          ports:
            - name: http
              containerPort: 20080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}