apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  user: {{ .Values.global.postgresql.postgresqlUsername | b64enc }}
  pass: {{ .Values.global.postgresql.postgresqlPassword | b64enc }}